### ISSUE TITLE
XML dependency

### ISSUE THREAD

**Issue by piecubed** [insinfo/essential_xlsx#1]
Please update your XML dependency, currently this package won't work with flutter_test, as that depends on a higher XML version.

**Comment by liuxiangxiang10** [comment]
Please update your XML dependency, currently this package won't work with excel, as that depends on a higher XML version.

**Comment by luizsavio** [comment]
Please update your XML dependency, currently this package won't work with excel, as that depends on a higher XML version.

**Comment by insinfo** [comment]
I have been very busy at work, but today I had time to update the package dependency.
I published version 1.1.0 with dependency update,
in case you want to make any pull request I will be available to merge.

https://pub.dev/packages/essential_xlsx
